trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  VERCEL_TOKEN: $(vercel_token) # Replace with your Azure DevOps secret

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: npm install -g vercel
    displayName: 'Install Vercel CLI'

  - script: npm install
    displayName: 'Install dependencies'
    workingDirectory: hoo-bank

  - script: npm run build
    displayName: 'Build project'
    workingDirectory: hoo-bank

  - script: |
      vercel pull --yes --environment=production --token=$(VERCEL_TOKEN)
      vercel build --prod --token=$(VERCEL_TOKEN)
      vercel deploy --prebuilt --prod --token=$(VERCEL_TOKEN)
    displayName: 'Deploy to Vercel'
    workingDirectory: hoo-bank
