trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  VERCEL_ORG_ID: '<your-vercel-org-id>'
  VERCEL_PROJECT_ID: '<your-vercel-project-id>'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
      npm run build
    displayName: 'Install deps and build'

  - script: |
      npm install -g vercel
      vercel pull --yes --environment=production --token=$(VERCEL_TOKEN)
      vercel build --prod --token=$(VERCEL_TOKEN)
      vercel deploy --prebuilt --prod --token=$(VERCEL_TOKEN)
    displayName: 'Deploy to Vercel'
